name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:base-devel
    steps:
      - name: Prepare
        run: |
          pacman-key --init
          pacman -Syu --noconfirm
          pacman -S --noconfirm git meson clang glslang libcap wlroots \
            sdl2 vulkan-headers libx11 libxcomposite libxrender libxres \
            libxtst libxkbcommon libdrm libinput wayland-protocols \
            xorg-xwayland pipewire
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Build with gcc
        run: |
          export CC=gcc CXX=g++
          meson build-gcc/ --werror --auto-features=enabled
          ninja -C build-gcc/
      - name: Prepare Release Packs
        run: |
          ls -alh ./build-gcc/
      - name: Upload to Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: gamescope-${{ env.GIT_SHA }}
          path: |
            ./build-gcc/gamescope
